GET http://localhost:5000/
###
GET http://localhost:5000/api/workingHours
###

POST http://localhost:5000/api/workingHours HTTP/1.1
content-type: application/json

{
    "text": "Luin kurssikirjan kappaleen 2",
    "amount": "4"
}

###
DELETE http://localhost:5000/api/workingHours/60eaee0b4d19a73424f27d36

###
GET http://localhost:5000/api/user
###
POST http://localhost:5000/api/user HTTP/1.1
content-type: application/json

{
    "username": "Kayttaja10",
    "name": "Kayttajannimi10",
    "passwordHash": "salasana6"
}

###
DELETE http://localhost:5000/api/user/60eeaaf31c382d02247f6cd8

###

POST http://localhost:5000/api/auth HTTP/1.1
content-type: application/json

{
    "username": "Kayttaja10",
    "passwordHash": "salasana6"
}

###
GET http://localhost:5000/api/auth/user
x-auth-token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZWZmODYxMDA3N2E4MTYzODliOTE4NiIsImlhdCI6MTYyNjM1NjcxMSwiZXhwIjoxNjI2MzYwMzExfQ.TC6s9GEyw6e296Olo_w_-WPDpqHXQzosjUerEGBG2Ho"

###

POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "Nimi21",
    "email": "kissa@koira",
    "password": "00000"
}

###

POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "sposti",
    "password": "123456"
}